apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-pr-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: sorakoro
          repo: pr-preview
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - preview
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "myapp-pr-{{number}}"
      labels:
        app.kubernetes.io/managed-by: applicationset
    spec:
      project: default
      source:
        repoURL: "https://github.com/sorakoro/pr-preview.git"
        targetRevision: "{{head_sha}}"
        path: k8s/overlays/pr-preview
        kustomize:
          patches:
            - target:
                kind: Ingress
                name: myapp
              patch: |
                apiVersion: networking.k8s.io/v1
                kind: Ingress
                metadata:
                  name: myapp
                spec:
                  rules:
                    - host: pr-{{number}}.localhost
                      http:
                        paths:
                          - path: /
                            pathType: Prefix
                            backend:
                              service:
                                name: myapp
                                port:
                                  number: 80
      destination:
        server: https://kubernetes.default.svc
        namespace: "pr-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
